#!/bin/bash
#create notes directory if it doesn't exist already
if [ ! -d ~/.notes ]
then
	mkdir ~/.notes
fi
#if called with no parameters. print the current date's note file if it exists	
if [ "$#" -lt 1 ]; 
then
	if [ -e ~/.notes/`date +"%m-%d-%Y"`.txt ] 
	then
		cat -n ~/.notes/`date +"%m-%d-%Y"`.txt
	else
		echo "There are no notes for the current date. You can add notes with note <notes to add>"
	fi
#if called with '-d <number>', delete line number specified
elif [ "$1" = "-d" ]
then
	if [ "$#" -gt 1 ]
	then
		if [ "$#" -lt 3 ]
		then
			sed -i $2d ~/.notes/`date +"%m-%d-%Y"`.txt
		else
			echo "-d can only be called with 3 arguments"
		fi
	else
		echo "You need to specify which line(s) to delete"
	fi
#If called with '-ef' parameter, erase current date's file
elif [ "$1" = "-ef" ]	
then
	if [ "$#" -lt 2 ]
	then
		rm ~/.notes/`date +"%m-%d-%Y"`.txt
	else
		echo "-ef cannot be called with any additional arguments"
	fi	
else
	echo $@ >> ~/.notes/`date +"%m-%d-%Y"`.txt
fi
